### ISSUE TITLE
Mapa metal- Blanca Estela

### ISSUE THREAD

**Issue by Blanca-estela-valerio-rivero** [SistemasTecTlaxiaco/actividad-1-mapa-mental-Blanca-estela-valerio-rivero#1]
![Mapa mental-Blanca Estela](https://user-images.githubusercontent.com/112271818/188059923-0733ac8e-4369-4daf-b62d-c1ee9b69a27d.png)

**Comment by josealfredo79** [comment]
Falta asignar calificacion

**Comment by gilbertovelasco1** [comment]
19%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
